### ISSUE TITLE
rename?

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf-merge#3]
is this not a chained union call rather than a merge? I want a turf-concat([features, features, featurecollection, geometry]) -> featurecollectionOfAll module and its name would be too close to this one.

**Comment by morganherlocker** [comment]
Yeah, I'm fine with repurposing this :+1:

**Comment by knownasilya** [comment]
denormalize? lol

**Comment by tmcw** [comment]
I am kind of skeptical of normalize/denormalize being repurposed for geometry operations - they have established meanings in the database world that don't map directly to these concepts.

**Comment by morganherlocker** [comment]
Yeah, this is not what comes to mind when I think "denormalize". Pretty much anything that is associated with RDBS concepts is a minefield of confusion.

**Comment by knownasilya** [comment]
Agreed. Maybe something about clustering? like marker clusters..

**Comment by tmcw** [comment]
I'm in favor of removing this module: I don't think it provides any value on top of union, and it adds a level of confusion.

**Comment by morganherlocker** [comment]
@tmcw I agree. This module papers over performance considerations that really should never be ignored.
